### PR TITLE
Support BE architectures

### LINKED ISSUE #51: Test failure on BE architectures
The rest suite of jplephem seems to fail on bigendian machines.
On a s390x machine we have the following error

```
=== python3.10 ===
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0+repack -- /usr/bin/python3.10
cachedir: .pytest_cache
rootdir: /tmp/autopkgtest-lxc.r516qzx2/downtmp/autopkgtest_tmp
collecting ... collected 46 items / 4 deselected / 42 selected

::TestDAFBytesIO::test_add_segment FAILED                                [  2%]
::TestDAFBytesIO::test_add_segment_when_summary_block_is_full FAILED     [  4%]
::TestDAFBytesIO::test_header PASSED                                     [  7%]
::TestDAFBytesIO::test_segments FAILED                                   [  9%]
::TestDAFRealFile::test_add_segment FAILED                               [ 11%]
::TestDAFRealFile::test_add_segment_when_summary_block_is_full FAILED    [ 14%]
::TestDAFRealFile::test_header PASSED                                    [ 16%]
::TestDAFRealFile::test_segments FAILED                                  [ 19%]
::TestDAFRealFileWithoutMMap::test_add_segment FAILED                    [ 21%]
::TestDAFRealFileWithoutMMap::test_add_segment_when_summary_block_is_full FAILED [ 23%]
::TestDAFRealFileWithoutMMap::test_header PASSED                         [ 26%]
::TestDAFRealFileWithoutMMap::test_segments FAILED                       [ 28%]
::SPKTests::test_array_tdb SKIPPED (the "de421.bsp" SPK file is not ...) [ 30%]
::SPKTests::test_array_tdb_array_tdb2 SKIPPED (the "de421.bsp" SPK f...) [ 33%]
::SPKTests::test_array_tdb_scalar_tdb2 SKIPPED (the "de421.bsp" SPK ...) [ 35%]
::SPKTests::test_ephemeris_end_date SKIPPED (the "de421.bsp" SPK fil...) [ 38%]
::SPKTests::test_jitter SKIPPED (the "de421.bsp" SPK file is not ava...) [ 40%]
::SPKTests::test_loading_array SKIPPED (the "de421.bsp" SPK file is ...) [ 42%]
::SPKTests::test_out_of_range_dates SKIPPED (the "de421.bsp" SPK fil...) [ 45%]
::SPKTests::test_scalar_tdb SKIPPED (the "de421.bsp" SPK file is not...) [ 47%]
::SPKTests::test_scalar_tdb2 SKIPPED (the "de421.bsp" SPK file is no...) [ 50%]
::SPKTests::test_scalar_tdb2_keyword SKIPPED (the "de421.bsp" SPK fi...) [ 52%]
::SPKTests::test_scalar_tdb_array_tdb2 SKIPPED (the "de421.bsp" SPK ...) [ 54%]
::SPKTests::test_scalar_tdb_keyword SKIPPED (the "de421.bsp" SPK fil...) [ 57%]
::SPKTests::test_segment_with_only_two_coefficients SKIPPED (the "de...) [ 59%]
::SPKTests::test_str SKIPPED (the "de421.bsp" SPK file is not available) [ 61%]
::SPKTests::test_too_early_date SKIPPED (the "de421.bsp" SPK file is...) [ 64%]
::SPKTests::test_too_late_date SKIPPED (the "de421.bsp" SPK file is ...) [ 66%]
::LegacyTests::test_array_tdb SKIPPED (the "de421" ephemeris package...) [ 69%]
::LegacyTests::test_array_tdb_array_tdb2 SKIPPED (the "de421" epheme...) [ 71%]
::LegacyTests::test_array_tdb_scalar_tdb2 SKIPPED (the "de421" ephem...) [ 73%]
::LegacyTests::test_ephemeris_end_date SKIPPED (the "de421" ephemeri...) [ 76%]
::LegacyTests::test_jitter SKIPPED (the "de421" ephemeris package ha...) [ 78%]
::LegacyTests::test_legacy_compute_method SKIPPED (the "de421" ephem...) [ 80%]
::LegacyTests::test_names SKIPPED (the "de421" ephemeris package has...) [ 83%]
::LegacyTests::test_scalar_tdb SKIPPED (the "de421" ephemeris packag...) [ 85%]
::LegacyTests::test_scalar_tdb2 SKIPPED (the "de421" ephemeris packa...) [ 88%]
::LegacyTests::test_scalar_tdb2_keyword SKIPPED (the "de421" ephemer...) [ 90%]
::LegacyTests::test_scalar_tdb_array_tdb2 SKIPPED (the "de421" ephem...) [ 92%]
::LegacyTests::test_scalar_tdb_keyword SKIPPED (the "de421" ephemeri...) [ 95%]
::LegacyTests::test_too_early_date SKIPPED (the "de421" ephemeris pa...) [ 97%]
::LegacyTests::test_too_late_date SKIPPED (the "de421" ephemeris pac...) [100%]

=================================== FAILURES ===================================
_______________________ TestDAFBytesIO.test_add_segment ________________________

self = <jplephem.test.TestDAFBytesIO testMethod=test_add_segment>

    def test_add_segment(self):
        f = self.sample_daf()
        d = DAF(f)
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 128)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:143: AssertionError
__________ TestDAFBytesIO.test_add_segment_when_summary_block_is_full __________

self = <jplephem.test.TestDAFBytesIO testMethod=test_add_segment_when_summary_block_is_full>

    def test_add_segment_when_summary_block_is_full(self):
        f = self.sample_daf()
        d = DAF(f)
    
        # Update n_summaries of final summary block to full.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(d.summaries_per_record))
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 200)
    
        # Reset n_summaries of that block back to its real value.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(1))
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:169: AssertionError
_________________________ TestDAFBytesIO.test_segments _________________________

self = <jplephem.test.TestDAFBytesIO testMethod=test_segments>

    def test_segments(self):
        f = self.sample_daf()
        d = DAF(f)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 2)
E       AssertionError: 0 != 2

/usr/lib/python3/dist-packages/jplephem/test.py:127: AssertionError
_______________________ TestDAFRealFile.test_add_segment _______________________

self = <jplephem.test.TestDAFRealFile testMethod=test_add_segment>

    def test_add_segment(self):
        f = self.sample_daf()
        d = DAF(f)
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 128)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:143: AssertionError
_________ TestDAFRealFile.test_add_segment_when_summary_block_is_full __________

self = <jplephem.test.TestDAFRealFile testMethod=test_add_segment_when_summary_block_is_full>

    def test_add_segment_when_summary_block_is_full(self):
        f = self.sample_daf()
        d = DAF(f)
    
        # Update n_summaries of final summary block to full.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(d.summaries_per_record))
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 200)
    
        # Reset n_summaries of that block back to its real value.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(1))
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:169: AssertionError
________________________ TestDAFRealFile.test_segments _________________________

self = <jplephem.test.TestDAFRealFile testMethod=test_segments>

    def test_segments(self):
        f = self.sample_daf()
        d = DAF(f)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 2)
E       AssertionError: 0 != 2

/usr/lib/python3/dist-packages/jplephem/test.py:127: AssertionError
_________________ TestDAFRealFileWithoutMMap.test_add_segment __________________

self = <jplephem.test.TestDAFRealFileWithoutMMap testMethod=test_add_segment>

    def test_add_segment(self):
        f = self.sample_daf()
        d = DAF(f)
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 128)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:143: AssertionError
____ TestDAFRealFileWithoutMMap.test_add_segment_when_summary_block_is_full ____

self = <jplephem.test.TestDAFRealFileWithoutMMap testMethod=test_add_segment_when_summary_block_is_full>

    def test_add_segment_when_summary_block_is_full(self):
        f = self.sample_daf()
        d = DAF(f)
    
        # Update n_summaries of final summary block to full.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(d.summaries_per_record))
    
        d.add_array(b'Summary Name 3', (121.0, 232.0, 343), [3003.0] * 200)
    
        # Reset n_summaries of that block back to its real value.
        d.file.seek(6 * 1024 + 16)
        d.file.write(Struct('d').pack(1))
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 3)
E       AssertionError: 0 != 3

/usr/lib/python3/dist-packages/jplephem/test.py:169: AssertionError
___________________ TestDAFRealFileWithoutMMap.test_segments ___________________

self = <jplephem.test.TestDAFRealFileWithoutMMap testMethod=test_segments>

    def test_segments(self):
        f = self.sample_daf()
        d = DAF(f)
    
        summaries = list(d.summaries())
        eq = self.assertEqual
>       eq(len(summaries), 2)
E       AssertionError: 0 != 2

/usr/lib/python3/dist-packages/jplephem/test.py:127: AssertionError
=========================== short test summary info ============================
FAILED ::TestDAFBytesIO::test_add_segment - AssertionError: 0 != 3
FAILED ::TestDAFBytesIO::test_add_segment_when_summary_block_is_full - Assert...
FAILED ::TestDAFBytesIO::test_segments - AssertionError: 0 != 2
FAILED ::TestDAFRealFile::test_add_segment - AssertionError: 0 != 3
FAILED ::TestDAFRealFile::test_add_segment_when_summary_block_is_full - Asser...
FAILED ::TestDAFRealFile::test_segments - AssertionError: 0 != 2
FAILED ::TestDAFRealFileWithoutMMap::test_add_segment - AssertionError: 0 != 3
FAILED ::TestDAFRealFileWithoutMMap::test_add_segment_when_summary_block_is_full
FAILED ::TestDAFRealFileWithoutMMap::test_segments - AssertionError: 0 != 2
============ 9 failed, 3 passed, 30 skipped, 4 deselected in 0.16s =============
```

See also: https://ci.debian.net/data/autopkgtest/testing/s390x/j/jplephem/25034274/log.gz

### PR DESCRIPTION
**Pull request by avalentino**
Closes #51

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
In spare moments this week I've started working to give jplephem a GitHub Actions workflow that will test both BE and LE, so that there's a way for me to confirm in the future that I don't break BE again. I'll report back when I have something working.

**Comment by avalentino** [comment]
Thanks @brandon-rhodes.
FYI, I have applied this patch the generate the Debian package that is currently in the Debian Sid main archive and now all the tests are passing in all the supported architectures including s390x, amd64, i385, several arm flavours, ppc64el and riscv64.

**Comment by avalentino** [comment]
@brandon-rhodes yes, the kind of error that I saw in Debian was similar to the ones in your log, but in my case only happened on BE architectures, while in your case it seems that the problem is on LE.
Another point is that on Debian we do not have Python 2.7.

Finally, I noticed that on Debian we have a larger number of skipped tests (30 vs 12):

https://ci.debian.net/data/autopkgtest/unstable/s390x/j/jplephem/26386272/log.gz

I will try to reproduce the issue locally and will provide feedback ASAP.

**Comment by avalentino** [comment]
> in my case only happened on BE architectures, while in your case it seems that the problem is on LE.

Sorry, this is not correct, the problem is still on BE architectures but be and Le seems to be swapped in your `ci.yaml` file

**Comment by avalentino** [comment]
Tests pass on s390x with Python 3

```
# uname -a
Linux c830a962bd3e 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 s390x GNU/Linux

# env PYTHONPATH=.. python3 -m unittest test -v
test_comment_command (test.CommandLineTests) ... ok
test_daf_command (test.CommandLineTests) ... ok
test_spk_command (test.CommandLineTests) ... ok
test_array_tdb (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_array_tdb_array_tdb2 (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_array_tdb_scalar_tdb2 (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_ephemeris_end_date (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_jitter (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_legacy_compute_method (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_names (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_scalar_tdb (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_scalar_tdb2 (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_scalar_tdb2_keyword (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_scalar_tdb_array_tdb2 (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_scalar_tdb_keyword (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_too_early_date (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_too_late_date (test.LegacyTests) ... skipped 'the "de421" ephemeris package has not been installed with "pip install de421"'
test_single_position (test.NAIF_DAF_Tests) ... ok
test_array_tdb (test.SPKTests) ... ok
test_array_tdb_array_tdb2 (test.SPKTests) ... ok
test_array_tdb_scalar_tdb2 (test.SPKTests) ... ok
test_ephemeris_end_date (test.SPKTests) ... ok
test_jitter (test.SPKTests) ... ok
test_loading_array (test.SPKTests) ... ok
test_out_of_range_dates (test.SPKTests) ... ok
test_scalar_tdb (test.SPKTests) ... ok
test_scalar_tdb2 (test.SPKTests) ... ok
test_scalar_tdb2_keyword (test.SPKTests) ... ok
test_scalar_tdb_array_tdb2 (test.SPKTests) ... ok
test_scalar_tdb_keyword (test.SPKTests) ... ok
test_segment_with_only_two_coefficients (test.SPKTests) ... ok
test_str (test.SPKTests) ... ok
test_too_early_date (test.SPKTests) ... ok
test_too_late_date (test.SPKTests) ... ok
test_add_segment (test.TestDAFBytesIO) ... ok
test_add_segment_when_summary_block_is_full (test.TestDAFBytesIO) ... ok
test_header (test.TestDAFBytesIO) ... ok
test_segments (test.TestDAFBytesIO) ... ok
test_add_segment (test.TestDAFRealFile) ... ok
test_add_segment_when_summary_block_is_full (test.TestDAFRealFile) ... ok
test_header (test.TestDAFRealFile) ... ok
test_segments (test.TestDAFRealFile) ... ok
test_add_segment (test.TestDAFRealFileWithoutMMap) ... ok
test_add_segment_when_summary_block_is_full (test.TestDAFRealFileWithoutMMap) ... ok
test_header (test.TestDAFRealFileWithoutMMap) ... ok
test_segments (test.TestDAFRealFileWithoutMMap) ... ok
jplephem ()
Doctest: jplephem ... /usr/lib/python3.10/doctest.py:2196: ResourceWarning: unclosed file <_io.BufferedReader name='de421.bsp'>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/doctest.py:2196: ResourceWarning: unclosed file <_io.BufferedReader name='moon_pa_de421_1900-2050.bpc'>
  test.globs.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok

----------------------------------------------------------------------
Ran 47 tests in 0.674s

OK (skipped=14)
```

**Comment by avalentino** [comment]
With Python 2 I have another problem that seems to be not connected to endianess:

```
# env PYTHONPATH=.. python2 -m unittest test   
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test.py", line 18, in <module>
    from jplephem import Ephemeris, commandline
  File "/workdir/git/jplephem/jplephem/commandline.py", line 102
    return ()
SyntaxError: 'return' with argument inside generator
```

**Comment by avalentino** [comment]
OK, after updating to the latest git version I was finally able to reproduce the issue and fix it.
A new patch is available in #53

**Comment by brandon-rhodes** [comment]
Thanks for the additional PR, it looks like it turned the build green! I'm happy that jplephem will now support users on other platforms.

Yes, I was startled to see that `return ()` line—what was it even there for? Maybe it was originally the whole function, as a placeholder, that I forgot to remove when I turned it into a generator? In any case I've removed it so Python 2.7 looks happy.

Thanks for working to make jplephem available in the Debian ecosystem!

**Pull request merged**
