### PR TITLE
Updated conda recipe

### PR DESCRIPTION
**Pull request by Juanlu001**
Follow-up of #10 and updated for #12.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
When I try applying this pull request, git tells me that it has already been applied, and the code does look to me like these edits have already been made — perhaps by 7884c8039aa2a7ae41848ca7b13964a4d9a0156c — and so I am going to go ahead and close it. Please re-open it if there are any lines here that still need to be applied to jplephem. Thanks!

**Comment by Juanlu001** [comment]
Oops, it was supposed to update the recipe for jplephem 2.5! Still, I uploaded a conda package to the conda-forge channel:

https://github.com/conda-forge/jplephem-feedstock/

If you want, instead of maintaining the recipe here I can add you as a maintainer there. It won't be a big burden for you, it just will be easier to keep you posted about the changes.

Right now you can install jplephem using:

```conda install jplephem --channel conda-forge```

**Comment by brandon-rhodes** [comment]
Yes, I would be very happy to have the recipe maintained over at conda-forge! Please add me as a maintainer, and when I see the notification, I will remove the old files from here in the jplephem repo. Thanks!

**Comment by Juanlu001** [comment]
Great! I think I've already updated the recipe, but please ping me if you do not receive the notification.

**Comment by brandon-rhodes** [comment]
It does look up to date. Thanks!

**Pull request closed without merging**
